import assert from "node:assert/strict";
import { readFileSync } from "node:fs";

const src = readFileSync(new URL("./install.ps1", import.meta.url), "utf8");

assert.match(src, /irm https:\/\/raw\.githubusercontent\.com\/luanwolf\/completeDiscordQuest\/main\/install\.ps1 \| iex/);
assert.match(src, /OpenJS\.NodeJS\.LTS/);
assert.match(src, /https:\/\/github\.com\/Vendicated\/Vencord\.git/);
assert.match(src, /src\\userplugins\\\$PluginName/);
assert.match(src, /https:\/\/github\.com\/luanwolf\/completeDiscordQuest\.git/);
assert.match(src, /pnpm.*install.*--frozen-lockfile/s);
assert.match(src, /'build'/);
assert.match(src, /scripts\/runInstaller\.mjs',\s*'--',\s*'--install',\s*'--branch',\s*'auto'/);
assert.match(src, /Nao rode como Administrador/);
assert.match(src, /Set-ExecutionPolicy -Scope Process -ExecutionPolicy Bypass/);
assert.match(src, /Resolve-Native/);
assert.match(src, /CommandType Application/);
assert.match(src, /"\$Name\.cmd"/);
assert.match(src, /Test-VencordSource/);
assert.match(src, /Find-VencordSource/);
assert.match(src, /Find-CheckoutFromInjection/);
assert.match(src, /reusando pasta existente/);
assert.match(src, /function Show-Banner/);
assert.match(src, /function Tui-Menu/);
assert.match(src, /\[OK\]/);
assert.match(src, /\[\*\]/);
assert.match(src, /NoPull/);
assert.match(src, /sem git pull/);
assert.match(src, /CompleteDiscordQuest/);
assert.match(src, /function Set-PluginEnabled/);
assert.match(src, /function Stop-Discord/);
assert.match(src, /function Start-Discord/);
assert.match(src, /Update\.exe/);
assert.match(src, /Test-GitDirty/);
assert.match(src, /status --porcelain/);
assert.match(src, /alinhando com o GitHub/);
assert.match(src, /fetch --depth 1 origin main/);
assert.match(src, /reset --hard FETCH_HEAD/);
assert.match(src, /git fetch falhou/);
assert.match(src, /update-ref HEAD FETCH_HEAD/);
assert.match(src, /robocopy/);
assert.match(src, /\$localSha -eq \$wantSha/);
assert.match(src, /if \(\$Yes\) \{ Start-Discord \}/);
assert.doesNotMatch(src, /sem git pull"/);
assert.equal((src.match(/\$MinNodeMajor = 22/) || []).length, 1);

console.log("install.check ok");
